# Generated by Django 3.2.4 on 2021-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210611_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['title', 'id'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
