# Generated by Django 3.2.4 on 2021-06-19 00:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210617_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='Расположение'),
        ),
    ]
